## Telegram Bot Configuration
telegram.bot.client_email=quicksnackcafe@quicksnackcafe-507707.iam.gserviceaccount.com
telegram.bot.url=https://api.telegram.org/bot
telegram.bot.token=TBU
telegram.bot.private_key=TBU

## Google Sheets Configuration
google.sheets.spreadsheet.id=19_p8rf3eooNhoKoZ9ZOYztGivnh1T69U6AhMfLGFI8U
google.sheets.creds_base64=TBU

## Whatsapp Configuration
whatsapp.api.url=https://graph.facebook.com/v17.0/110174187168155
whatsapp.api.verify.token=TBU